### ISSUE TITLE
JSON support?

### ISSUE THREAD

**Issue by deadlyicon** [logentries/le_ruby#50]
messages logged as JSON are not properly parsed by logentries.com

```ruby
Rails.logger.info({some:'json',data:'here'}.to_json)
```

**Comment by nguyenmv2** [comment]
I have the same issue with lograge. Is this issue resolved ?

**Comment by angelacode** [comment]
This issue still unresolved?

**Comment by stefansedich** [comment]
From what I could tell the logger was putting things like the severity in front of the JSON logs with a timestamp and it was causing issues, I have been working on a semantic logger for Ruby which has nice support for JSON logging to logentries using a provided sink, if anyone is interested in trying it out let me know.

**Comment by tilfin** [comment]
I am making Ougai (https://github.com/tilfin/ougai) that is a Ruby JSON logger compatible with Bunyan (for Node.js)

I ran the following code:
```
require 'rubygems'
require 'ougai'
require 'le'

LOGENTRIES_TOKEN = 'xxxx-xxxx-xxxx-xxxx-xxxxxxx'
host = Le::Host.new(LOGENTRIES_TOKEN, false, false, true, ['', 10000], '', [false, ''], nil, false)

logger = Ougai::Logger.new(host)
logger.debug('Debug!', custom_data: { id: 1, name: 'something' })

begin
  1 / 0
rescue => e
  logger.error(e, 'error occurred')
end

logger.close
```

Logentries output the followings:
```
[D19LTB]{"name":"main","hostname":"zetaplus.local","pid":50076,"level":20,"time":"2017-02-09T17:41:39.121+09:00","v":0,"custom_data":{"id":1,"name":"something"},"msg":"Debug!"}
[RCMW9F]{"name":"main","hostname":"zetaplus.local","pid":50076,"level":50,"time":"2017-02-09T17:41:39.121+09:00","v":0,"msg":"error occurred","err":{"name":"ZeroDivisionError","message":"divided by 0","stack":"main.rb:13:in `/'\n  main.rb:13:in `<main>'"}}
```

Unfortunately, 'Expand JSON' display function does not work because Le::Host::Http is adding a token to the head of messages.

This module should be provided the plain simply socket client as Logger::LogDevice.

**Comment by roybotnik** [comment]
The problem is the code in http that adds a 'random message id' to the beginning of every log message. I have no idea what that is for.

**Comment by roybotnik** [comment]
Stripping the message before prepending this identifier fixes the issue:

```
module Le
  module Host
    class HTTP
      def write(message)

        if !host_id.empty?
          message = "#{message} #{ host_id }"
        end

        if host_name_enabled
          message="#{message} #{ host_name }"
        end

        if @local
          @logger_console.add(Logger::Severity::UNKNOWN, message)
        end
        # Strip leading/trailing newlines to prevent adding message ID for no reason.
        if message.strip.scan(/\n/).empty? 
          @queue << "#{ @token } #{ message } \n"
        else
          @queue << "#{ message.gsub(/^/, "\1#{ @token } [#{ random_message_id }] ") }\n"
        end

        if @started
          check_async_thread
        else
          start_async_thread
        end
      end
    end
  end
end
```

Although it would be nice to remove or have the option to turn the message ID off altogether. Using tagged logging provides the same thing (giving multi-line errors an ID so you can relate them) but works better since this code results in a different 'message ID' being prepended if the logger is called multiple times, like when an exception is raised.

**Comment by tilfin** [comment]
It is not good that not `Host.formatter` but `Host::Http.write` appends trailing newline to the message. but I implemented [Ougai](https://github.com/tilfin/ougai)'s JSON formatter could also serialize a message without newline.

It made it possible to handle JSON logs as JSON on Logentries web console!
https://github.com/tilfin/ougai/wiki/Forward-logs-to-Logentries
I expect `Le::Host.new` arguments should be more simply.
